FROM python:3.9.7-alpine3.14

WORKDIR /messenger

COPY requirements.txt messenger/* /messenger/
COPY common /messenger/common

RUN apk add tzdata gcc musl-dev zlib-dev && \
    python3 -m pip install -r /messenger/requirements.txt && \
    cp /usr/share/zoneinfo/US/Eastern /etc/localtime && \
    echo "US/Eastern" > /etc/timezone && \
    touch /messenger/log.txt && \
    chown -R 69:420 /messenger/log.txt

USER 69:420

ENTRYPOINT python3 /messenger/
