apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: polls.saltbot.greeson.xyz
spec:
  group: saltbot.greeson.xyz
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
              author:
                type: string
              channel:
                type: string
              prompt:
                type: string
              choices:
                type: array
                items:
                  type: string
              expiry:
                type: integer
                format: int64
              votes:
                type: array
                items:
                  type: object
                  properties:
                    choice:
                      type: string
                    choosers:
                      type: array
                      items:
                        type: string
  scope: Namespaced
  names:
    plural: polls
    singular: poll
    kind: Poll
